name: Publish NuGet

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=<Version>).*(?=</Version>)' StreamDeck.Client.Csharp.Core/StreamDeck.Client.Csharp.Core.csproj)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack --no-build -o nupkg /p:PackageVersion=$PACKAGE_VERSION
      - name: Publish
        run: dotnet nuget push "nupkg/*.nupkg" --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
